# Generated by Django 5.0.6 on 2024-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel_number',
            field=models.IntegerField(),
        ),
    ]
