# Generated by Django 5.0.6 on 2024-05-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_client_data_registr_alter_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_enter',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
